spring:
  cloud:
    consul: # Consul 服務註冊與發現配置
      discovery:
        ip-address: ${SERVICE_IP:127.0.0.1} # 動態 IP 地址
  security: # OAuth2 客戶端配置
    oauth2:
      client:
        registration: # 註冊客戶端信息
          oauth:
            provider: gss # 自定義 OAuth2 提供者名稱
            client-id: ${OAUTH_CLIENT_ID:oauth} # 客戶端 ID，通過環境變數配置
            client-secret: ${OAUTH_CLIENT_SECRET:secret} # 客戶端密鑰，通過環境變數配置
            authorization-grant-type: authorization_code # 授權類型
            redirect-uri: ${BASE_URL:http://localhost:8080}/oauth/callback # 重定向 URI（開發環境）
        provider: # OAuth2 提供者相關 URL
          gss:
            authorization-uri: https://member.vikosmos.com/cas/oauth2.0/authorize # 授權 URL
            token-uri: https://member.vikosmos.com/cas/oauth2.0/token # 令牌發放 URL
            user-info-uri: https://member.vikosmos.com/cas/oauth2.0/profile # 用戶信息 URL

auth: # 自定義認證相關配置
  registration-id: oauth # OAuth2 註冊 ID
  redirect:
    final-uri: ${FINAL_URI:http://localhost:3000/} # 認證成功後重定向的 URI
  account-center: # 外部帳號中心相關配置
    check-token-url: ${CHECK_TOKEN_URL:https://member.vikosmos.com/cas/oauth2.0/introspect} # 檢查 Token 的 URL
  issuer: ${AUTH_ISSUER:http://localhost:8080/authn}
  token:
    max-retries: ${TOKEN_REFRESH_MAX_RETRIES:3} # 最大重試次數（建議值：1-5）
    buffer-time-seconds: 3600 # 緩衝時間（秒），此處為1小時
    cache-duration-days: 7 # 緩存有效期配置（默認為 7 天）
    refresh-token-expiration-ms: ${TOKEN_REFRESH_EXPIRATION:604800000} # Refresh Token 的過期時間（7 天，支持覆蓋）
    access-token-expiration-ms: ${ACCESS_TOKEN_EXPIRATION:3600000}   # Access Token 的過期時間（1 小時，支持覆蓋）

jwt:
  key:
    id: ec-key-1       # 金鑰的唯一標識符 (Key ID, kid)，通常用於區分多個金鑰
    curve: P-256       # 橢圓曲線 (Elliptic Curve, EC) 的類型，這裡使用的是 P-256 曲線（也稱為 secp256r1），
                       # 它是一種常用的橢圓曲線，提供良好的性能和安全性，適合生成和驗證 JWT 簽名

key:
  directory: ${KEY_DIRECTORY:keys/} # 金鑰存放目錄
  private-file: ${KEY_PRIVATE_FILE:ec_private.key} # 私鑰文件名
  public-file: ${KEY_PUBLIC_FILE:ec_public.key} # 公鑰文件名

bizform: # BizForm 外部系統 API 配置
  api:
    base-url: ${BIZFORM_API_BASE_URL:https://bizform.vikosmos.com} # BizForm API 基礎 URL
    login-endpoint: /Backend/api/account/login # 登錄端點
