server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: todo-service
          uri: http://localhost:8081
          predicates:
            - Path=/todo/**
          filters:
            - StripPrefix=1
        - id: authBridge-service
          uri: http://localhost:8086
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - RedirectUriValidationFilter
        - id: bizform-service
          uri: http://localhost:8082
          predicates:
            - Path=/bizform/**
          filters:
            - StripPrefix=1
        - id: crm-service
          uri: http://localhost:8083
          predicates:
            - Path=/crm/**
          filters:
            - StripPrefix=1
        - id: report-service
          uri: http://localhost:8084
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1

  data:
    redis:
      host: localhost
      port: 6380
      password: # 如果需要密碼，填寫這裡
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms  # 可選：配置最大等待時間

app:
  security:
    allowed-redirect-uris:
      - "http://localhost:8086/oauth/callback"
      - "http://localhost:8081/home"

cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: "always"