server:
  port: 8080 # 設定 API Gateway 的服務埠號

spring:
  cloud:
    gateway:
      routes:
        - id: todo-service
          uri: http://localhost:8081
          predicates:
            - Path=/todo/**
          filters:
            - StripPrefix=1
        - id: authBridge-service
          uri: http://localhost:8086
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - RedirectUriValidationFilter
        - id: bizform-service
          uri: http://localhost:8082
          predicates:
            - Path=/bizform/**
          filters:
            - StripPrefix=1
        - id: crm-service
          uri: http://localhost:8083
          predicates:
            - Path=/crm/**
          filters:
            - StripPrefix=1
        - id: report-service
          uri: http://localhost:8084
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1

  data:
    redis:
      host: localhost # Redis 主機
      port: 6380      # Redis 埠號
      password: # 如果需要密碼，填寫這裡
      lettuce:
        pool:
          max-active: 50      # 從較小值開始測試
          max-idle: 15        # 控制空閒連接數
          min-idle: 5         # 預熱部分連接，保證有可用連接
          max-wait: 2000ms    # 減少等待時間

app:
  security:
    allowed-redirect-uris:
      - "http://localhost:8086/oauth/callback"
      - "http://localhost:8081/home" # 定義允許的重定向 URI

cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"

# 配置 WebClient 的 Base URL
auth:
  service:
    base-url: http://auth-server:8086