server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: todo-service
          uri: http://localhost:8081
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1
        - id: authBridge-service
          uri: http://localhost:8086
          predicates:
            - Path=/authBridge-service/**
          filters:
            - StripPrefix=1
        - id: bizform-service
          uri: http://localhost:8082
          predicates:
            - Path=/bizform-service/**
          filters:
            - StripPrefix=1
        - id: crm-service
          uri: http://localhost:8083
          predicates:
            - Path=/crm-service/**
          filters:
            - StripPrefix=1
        - id: report-service
          uri: http://localhost:8084
          predicates:
            - Path=/report-service/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: "always"