server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: todo-service
          uri: http://localhost:8081
          predicates:
            - Path=/todo/**
          filters:
            - StripPrefix=1
        - id: authBridge-service
          uri: http://localhost:8086
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - RedirectUriValidationFilter
        - id: bizform-service
          uri: http://localhost:8082
          predicates:
            - Path=/bizform/**
          filters:
            - StripPrefix=1
        - id: crm-service
          uri: http://localhost:8083
          predicates:
            - Path=/crm/**
          filters:
            - StripPrefix=1
        - id: report-service
          uri: http://localhost:8084
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1
app:
  security:
    allowed-redirect-uris:
      - "http://localhost:8086/oauth/callback"
      - "http://localhost:8081/home"

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: "always"