server:
  port: 8086

spring:
  security:
    oauth2:
      authorization-server:
        jwt:
          key:
            private-key-location: classpath:keys/private-key.pem
            public-key-location: classpath:keys/public-key.pem

authorization:
  issuer: http://localhost:8086

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: when_authorized # 更安全的配置
