server:
  port: 8086

spring:
  security:
    oauth2:
      client:
        registration:
          oauth:
            provider: gss
            client-id: oauth
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8086/oauth/callback # 開發環境 URI
          token-exchange:
            provider: gss
            client-id: oauth
            client-secret: secret
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            client-authentication-method: client_secret_basic
            scope:
              - bizform.read
              - crm.read
        provider:
          gss:
            authorization-uri: https://member.vikosmos.com/cas/oauth2.0/authorize
            token-uri: https://member.vikosmos.com/cas/oauth2.0/token
            user-info-uri: https://member.vikosmos.com/cas/oauth2.0/profile

  datasource:
    url: jdbc:mysql://localhost:3306/vitalbridge
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Gss12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update # 開發環境使用 update，生產環境改為 none
    open-in-view: false # 禁用此功能以提高性能

  data:
    redis:
      host: localhost
      port: 6379
      password: # 若 Redis 設置密碼，填寫這裡
      lettuce:
        pool:
          max-active: 100  # 最大連接數，同時支持的最大併發數
          max-idle: 20     # 最大空閒連接數，閒置超過這個值會被釋放
          min-idle: 10     # 最小空閒連接數，保證預熱可用連接
          max-wait: 3000ms # 連接池耗盡時最大等待時間，避免無限等待

crm:
  api-key: your-crm-api-key

auth:
  redirect:
    final-uri: "http://localhost:8081/home"
  account-center:
    check-token-url: "https://member.vikosmos.com/cas/oauth2.0/introspect"

management:
  endpoints:
    web:
      exposure:
        include: health, metrics # 生產環境建議限制只包含必要的端點，例如 health, metrics