server:
  port: 8086

spring:
  security:
    oauth2:
      client:
        registration:
          oauth:
            provider: gss
            client-id: oauth
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8086/login/oauth2/code/oauth
        provider:
          gss:
            authorization-uri: https://member.vikosmos.com/cas/oauth2.0/authorize
            token-uri: https://member.vikosmos.com/cas/oauth2.0/token
            user-info-uri: https://member.vikosmos.com/cas/oauth2.0/profile

  datasource:
    url: jdbc:mysql://localhost:3306/vitalbridge?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: # 如果需要密碼，填寫這裡
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms  # 可選：配置最大等待時間

auth:
  redirect:
    final-uri: "http://localhost:8081/home"

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      default: # 或者是特定的 Feign Client 名稱
        connect-timeout: 5000  # 連接超時 5 秒
        read-timeout: 5000     # 讀取超時 5 秒
