server:
  port: 8085 # 微服務端口

spring:
  application:
    name: authorization-service # 微服務名稱，用於服務註冊與發現
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name} # 動態服務名稱
        health-check-path: /actuator/health # 健康檢查端點
        health-check-interval: 15s # 健康檢查間隔
        health-check-timeout: 5s # 健康檢查超時
        ip-address: ${HOST_IP:127.0.0.1} # 動態 IP 地址
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port} # 唯一實例 ID