server:
  port: 8086
spring:
  security:
    oauth2:
      client:
        registration:
          oauth:
            provider: gss
            client-id: oauth
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8086/login/oauth2/code/oauth
        provider:
          gss:
            authorization-uri: https://member.vikosmos.com/cas/oauth2.0/authorize
            token-uri: https://member.vikosmos.com/cas/oauth2.0/token
            user-info-uri: https://member.vikosmos.com/cas/oauth2.0/profile
  data:
    redis:
      host: localhost
      port: 6379
      password: # 如果需要密碼，填寫這裡
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms  # 可選：配置最大等待時間

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: when_authorized # 更安全的配置
