server:
  port: 8085 # 微服務端口

spring:
  application:
    name: authorization-service # 微服務名稱，用於服務註冊與發現
  cloud:
    consul:
      discovery:
        hostname: localhost # 或指定靜態 IP，例如 127.0.0.1
        service-name: ${spring.application.name} # 服務名稱，動態化配置
        health-check-path: /actuator/health # 健康檢查端點
        health-check-interval: 15s # 健康檢查間隔
        instance-id: ${spring.application.name}-${server.port} # 唯一實例 ID