server:
  port: 8086

spring:
  security:
    oauth2:
      client:
        registration:
          AuthBridge-Service:
            provider: spring
            client-id: oauth
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/AuthBridge-Service
            scope: openid,profile
            client-name: Spring
        provider:
          spring:
            authorization-uri: https://member.vikosmos.com/cas/oauth2.0/authorize
            token-uri: https://member.vikosmos.com/cas/oauth2.0/token
            user-info-uri: https://member.vikosmos.com/cas/oauth2.0/profile

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: when_authorized # 更安全的配置
