server:
  port: 8888

spring:
  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=10m # Cache 初始容量、最大容量與過期時間配置

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info # 暴露 prometheus, health 和 info 端點
  endpoint:
    health:
      show-details: always # 健康檢查詳情總是可見