server:
  port: 8888 # Config Server 運行的端口

spring:
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name} # 動態服務名稱
        health-check-path: /actuator/health # 健康檢查端點
        health-check-interval: 15s # 健康檢查間隔
        health-check-timeout: 5s # 健康檢查超時
        ip-address: ${HOST_IP:127.0.0.1} # 動態 IP 地址
        instance-id: ${spring.application.name}-${HOST_IP:127.0.0.1}-${server.port} # 唯一實例 ID
  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=10m # Cache 初始容量、最大容量與過期時間配置
  security:
    user:
      name: ${SECURITY_USER_NAME:admin} # 基本認證用戶名稱，支持環境變數
      password: ${SECURITY_USER_PASSWORD:Gss12345678} # 基本認證用戶密碼，支持環境變數（建議通過 Vault 或環境變數管理）