server:
  port: 8888 # Config Server 運行的埠號

spring:
  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=10m # Cache 初始容量、最大容量與過期時間配置
  security:
    user:
      name: admin # 基本認證用戶名稱
      password: Gss12345678 # 基本認證用戶密碼（建議透過環境變數或 Vault 管理）