server:
  port: 8081 # 微服務端口

spring:
  application:
    name: ${APP_NAME:todo-service} # 動態應用名稱，支持多環境
  cloud:
    consul: # Consul 配置
      discovery:
        hostname: localhost # 或指定靜態 IP，例如 127.0.0.1
        service-name: ${spring.application.name} # 服務名稱，動態化配置
        health-check-path: /actuator/health # 健康檢查端點
        health-check-interval: 15s # 健康檢查間隔，適當減少對 Consul 的壓力
        instance-id: ${spring.application.name}-${server.port} # 唯一實例 ID