spring:
  cloud:
    consul:
      discovery:
        healthCheckUrl: http://authz-service:${server.port}/actuator/health
        ip-address: ${SERVICE_IP:${spring.cloud.client.ip-address}}

  data:
    redis:
      host: ${REDIS_HOST:auth_redis} # 動態化 Redis 主機，支持多環境配置
      port: ${REDIS_PORT:6379}      # Redis 默認端口
      password: ${REDIS_PASSWORD:GssAuthRedis111}  # Redis 密碼（如果有）
      timeout: 5s  # 設定連線超時為 5 秒
      lettuce:
        pool:
          max-active: 50      # 最大連接數
          max-idle: 15        # 最大空閒連接數
          min-idle: 5         # 最小空閒連接數
          max-wait: 2000ms    # 連接等待時間