server:
  port: 8085

spring:
  application:
    name: ${APP_NAME:authz-service}
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}
