server:
  port: 8083

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${server.port}

  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=10m # Cache 初始容量、最大容量與過期時間配置

  data:
    redis:
      host: ${REDIS_HOST:localhost} # 動態化 Redis 主機，支持多環境配置
      port: ${REDIS_PORT:6380}      # Redis 默認端口
      password: ${REDIS_PASSWORD:}  # Redis 密碼（如果有）
      lettuce:
        pool:
          max-active: 50      # 最大連接數
          max-idle: 15        # 最大空閒連接數
          min-idle: 5         # 最小空閒連接數
          max-wait: 2000ms    # 連接等待時間