server:
  port: 8888

spring:
  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=10m

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: "always"