spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/authn} # JWT 驗證的簽發者 URI
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/authn/jwks/publicKey} # JWK 公鑰 URI，用於驗證 JWT 簽名
  cloud:
    consul:
      discovery:
        ip-address: ${HOST_IP:${spring.cloud.client.ip-address}}
        hostname: ${HOSTNAME:${spring.cloud.client.hostname}}

jwt:
  issuer: ${JWT_ISSUER_URI:http://localhost:8080/authn}
  jwk-set-uri: http://localhost:8080/authn/jwks/publicKey
  signature-algorithm: ES256
  valid:
    audiences: ${JWT_VALID_AUDIENCES:http://localhost:8080}