spring:
  cloud:
    consul:
      discovery:
        ip-address: ${SERVICE_IP:${spring.cloud.client.ip-address}} # IP 地址，優先使用外部傳入的環境變數

jwt:
  issuer: ${JWT_ISSUER_URI:http://localhost:8080/authn} # JWT 簽發者的 URI
  jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/authn/jwks/publicKey} # JWK 公鑰的 URI
  signature-algorithm: ES256 # 使用 EC（橢圓曲線）簽名算法
  time-skew:
    seconds: 60 # 時間偏移，允許 JWT 驗證時容忍的時差
  valid:
    audiences: ${JWT_VALID_AUDIENCES:http://localhost:8080} # JWT 的受眾驗證