spring:
  cloud:
    consul:
      discovery:
        ip-address: ${SERVICE_IP:${spring.cloud.client.ip-address}}
        hostname: ${HOSTNAME:${spring.cloud.client.hostname}}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${spring.cloud.client.ip-address}:${server.port}/authn
          jwk-set-uri: http://${spring.cloud.client.ip-address}:${server.port}/authn/ec/publicKey