server:
  address: 0.0.0.0
  port: 8087

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${server.port}

app:
  security:
    public-paths:
      - "/actuator/health"
      - "/actuator/prometheus"