server:
  port: 8087

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}

app:
  security:
    public-paths:
      - "/demo"
      - "/actuator/health"
      - "/actuator/prometheus"