server:
  port: 8081

spring:
  loadbalancer:
    cache:
      enabled: true
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}

