spring:
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
        ip-address: ${SERVICE_IP:127.0.0.1}

  data:
    redis:
      host: ${REDIS_HOST:localhost} # 動態化 Redis 主機，支持多環境配置
      port: ${REDIS_PORT:6379}      # Redis 默認端口
      password: ${REDIS_PASSWORD:GssAuthRedis111}  # Redis 密碼（如果有）
      timeout: 5s  # 設定連線超時為 5 秒
      lettuce:
        pool:
          max-active: 50      # 最大連接數
          max-idle: 15        # 最大空閒連接數
          min-idle: 5         # 最小空閒連接數
          max-wait: 2000ms    # 連接等待時間

jwt:
  jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/authn/jwks/publicKey}

springdoc:
  swagger-ui:
    enabled: false       # 關閉 Swagger UI 頁面（/swagger-ui.html），避免在生產環境暴露 API 文件
  api-docs:
    path: /v3/blacklist-docs  # 根據每個微服務設計自己的前綴