spring:
  cloud:
    consul:
      discovery:
        healthCheckUrl: http://todo-service:${server.port}/actuator/health
        ip-address: ${SERVICE_IP:${spring.cloud.client.ip-address}}

  jwt:
    jwk-set-uri: http://${spring.cloud.client.ip-address}:8080/authn/jwks/publicKey