spring:
  cloud:
    consul:
      discovery:
        healthCheckUrl: http://todo-service:${server.port}/actuator/health
        ip-address: ${SERVICE_IP:${spring.cloud.client.ip-address}}

  jwt:
    jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/authn/jwks/publicKey}