spring:
  cloud:
    consul:
      discovery:
        ip-address: ${SERVICE_IP:${spring.cloud.client.ip-address}}
        hostname: ${HOSTNAME:${spring.cloud.client.hostname}}

  jwt:
    jwk-set-uri: http://localhost:8080/authn/jwks/publicKey