spring:
  cloud:
    consul:
      discovery:
        healthCheckUrl: http://authp-service:${server.port}/actuator/health
        ip-address: ${SERVICE_IP:${spring.cloud.client.ip-address}}

  datasource: # 數據源配置
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/vitalcasebridge # MySQL 地址
    username: ${MYSQL_USERNAME:root} # 數據庫用戶名，動態化設置
    password: ${MYSQL_PASSWORD:} # 數據庫密碼，建議通過環境變數配置
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 驅動類

  jpa: # JPA 和 Hibernate 配置
    properties:
      hibernate:
        show_sql: true # 顯示 SQL 語句（開發環境開啟）
        format_sql: true # 格式化 SQL 語句（開發環境開啟）
    hibernate:
      ddl-auto: update # 生產環境建議使用 none
    open-in-view: false # 禁用 Open Session In View，以提升性能

bizform:
  service:
    url: ${BIZFORM_API_BASE_URL:https://bizform.vikosmos.com}

# 指定使用 log4j2-logstash.xml 作為 logging 設定檔，啟用 Logstash 輸出
logging:
  config: classpath:log4j2-logstash.xml