spring:
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health # 健康檢查端點
        ip-address: ${SERVICE_IP:127.0.0.1} # 動態 IP 地址

# 指定使用 log4j2-logstash.xml 作為 logging 設定檔，啟用 Logstash 輸出
logging:
  config: classpath:log4j2-logstash.xml